= WebDriverManager
Boni García
:revnumber: {project-version}

== Motivation
https://seleniumhq.github.io/docs/site/en/webdriver/[Selenium WebDriver] is a library that allows controlling web browsers programmatically. It provides a cross-browser API that can be used to drive web browsers (e.g., Chrome, Edge, or Firefox, among others) using different programming languages (e.g., Java, JavaScript, Python, C#, or Ruby). The primary use of Selenium WebDriver is implementing automated tests for web applications.

Selenium WebDriver carries out the automation using the native support of each browser. For this reason, we need to place a binary file called *driver* between the test using the Selenium WebDriver API and the browser to be controlled. Examples of drivers for major web browsers nowadays are https://chromedriver.chromium.org/[chromedriver] (for Chrome), https://github.com/mozilla/geckodriver/[geckodriver] (for Firefox), or https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/[msedgedriver] (for Edge).

From a practical point of view, we need to carry out a _driver management process_ to use Selenium WebDriver. This process consists on:

1. Download. Drivers are platform-specific binary files. Therefore, we need to identify the driver type we need (e.g., chromedriver if we want to use Chrome), the operating system (typically, Windows, Linux, or Mac OS), the architecture (typically, 32 or 64 bits), and very important, the version. Each driver release is usually compatible with a given browser version(s). For this reason, we need to find out the correct driver version for a specific browser version.
2. Setup. Once we have downloaded the driver to our computer, we need to provide a way to locate this driver from our Selenium WebDriver tests. In Java, this setup can be done in two different ways. First, we can add the driver location to our +PATH+ environmental variable. Second, we can use _Java system properties_ to export the driver path. Each driver path should be identified using a given system property, as follows:
+
[source,java]
----
System.setProperty("webdriver.chrome.driver", "/path/to/chromedriver");
System.setProperty("webdriver.gecko.driver", "/path/to/geckodriver");
System.setProperty("webdriver.edge.driver", "/path/to/msedgedriver");
System.setProperty("webdriver.opera.driver", "/path/to/operadriver");
System.setProperty("webdriver.ie.driver", "C:/path/to/IEDriverServer.exe");
----
3. Maintenance. Last but not least, we need to warranty the compatibility between driver and browser in time. This step is relevant since modern browsers automatically upgrade themselves (i.e., they are _evergreen_ browsers), and for this reason, the compatibility driver-browser is not warranted in the long run. For instance, when a WebDriver test using Chrome faces a driver incompatibility, it reports the following error message: "_this version of chromedriver only supports chrome version N_." As you can see in https://stackoverflow.com/search?q=this+version+of+chromedriver+only+supports+Chrome+version[StackOverflow], this is a recurrent problem for manually managed drivers (chromedriver in this case).

*WebDriverManager* is an open-source Java library that carries out this <<driver-management,driver management process>> in a fully automated manner. In addition, as of version 5, WebDriverManager provides other relevant features, such as the ability to <<browser-finder,find if a browser is installed>> in the system, <<webdriver-builder,build WebDriver objects>> (such as `ChromeDriver,` `FirefoDriver,` etc.), and the capability to run <<browsers-in-docker,browsers in Docker containers>> containers seamlessly.

== Setup
Using WebDriverManager is very easy. First, you need to import the dependency in your project (typically as _test_ dependency). In Maven, it is done as follows:

[source,xml]
<dependency>
    <groupId>io.github.bonigarcia</groupId>
    <artifactId>webdrivermanager</artifactId>
    <version>5.0.0</version>
    <scope>test</scope>
</dependency>

The dependency (typically _test_) to be declared in a Gradle project is as follows:

[source,json]
dependencies {
    testImplementation("io.github.bonigarcia:webdrivermanager:5.0.0")
}

Then, you need to declare _Selenium-Jupiter_ extension in your JUnit 5 test, simply annotating your test with `@ExtendWith(SeleniumJupiter.class)`. Finally, you need to include one or more parameters in your `@Test` methods (or constructor) whose types implements the `WebDriver` interface (e.g. `ChromeDriver` to use Chrome, `FirefoxDriver` for Firefox, and so for). That's it. _Selenium-Jupiter_ control the lifecycle of the `WebDriver` object internally, and you just need to use the `WebDriver` object in your test to drive the browser(s) you want. For example:

[source,java]
----
include::../../test/java/io/github/bonigarcia/wdm/test/chrome/ChromeTest.java[tags=snippet-in-doc,indent=0]
----

NOTE: As of JUnit 5.1, extensions can be registered programmatically via `@RegisterExtension` or automatically via Java's `ServiceLoader`. Both mechanisms can be used with _Selenium-Jupiter_.

== Features

=== Driver Management
Under construction.

==== Resolution Algorithm
Under construction.

=== Browser Finder
Under construction.

=== WebDriver Builder
Under construction.

=== Browsers in Docker
Under construction.

==== Recordings
Under construction.

==== Remote Desktop
Under construction.

== Other Usages

=== WDM CLI

Under construction.

=== WDM Server

Under construction.

=== WDM in Docker

Under construction.

=== WDM Agent

Under construction.

== Examples

Under construction.

== Configuration

Under construction.

== Known issues

Under construction.

[discrete]
==== HTTP response code 403

Under construction.

[discrete]
==== Testing localhost

Under construction.

[discrete]
==== Docker and chromedriver 92+

Under construction.

== Support

There are several ways to get in touch with WebDriverManager:

* Questions about WebDriverManager are supposed to be discussed in https://stackoverflow.com/questions/tagged/webdrivermanager_java[StackOverflow], using the tag _webdrivermanager_java_.
* Comments, suggestions and bug-reporting should be done using the https://github.com/bonigarcia/webdrivermanager/issues[GitHub issues].
* If you think WebDriverManager can be enhanced, consider contribute to the project by means of a  https://github.com/bonigarcia/webdrivermanager/pulls[pull request].

== Contributing

To do.

== Further documentation

To do.

== About
WebDriverManager (Copyright © 2017-2021) is an open-source project created and maintained by https://bonigarcia.org/[Boni García] (https://twitter.com/boni_gg[@boni_gg]), licensed under the terms of https://www.apache.org/licenses/LICENSE-2.0[Apache 2.0 License]. This documentation (also available in link:webdrivermanager.pdf[PDF]) is released under the terms of https://creativecommons.org/licenses/by-nc-sa/2.0/[CC BY-NC-SA 2.0].
